### ISSUE TITLE
SyntaxWarning: invalid escape sequence

### ISSUE THREAD

**Issue by aNaoy** [longld/peda#177]
There's a SyntaxWarning since Python 3.12 using peda.py at GDB startup. This was introduced [here](https://docs.python.org/dev/whatsnew/3.12.html#other-language-changes) when the DeprecationWarning was upgraded to SyntaxWarning.

> /usr/share/peda/peda.py:151: SyntaxWarning: invalid escape sequence '\['
>   p = re.compile("(.*)\[(.*)\]") # DWORD PTR [esi+eax*1]
> /usr/share/peda/peda.py:373: SyntaxWarning: invalid escape sequence '\s'
>   p = re.compile(".*exec file:\s*`(.*)'")
> /usr/share/peda/peda.py:550: SyntaxWarning: invalid escape sequence '\d'
>   p = re.compile("^(\d*)\s*(.*breakpoint)\s*(keep|del)\s*(y|n)\s*(0x[^ ]*)\s*(.*)")
> [...]
> 

It should be fixed by using raw string literals (r"...").

**Comment by oknyshuk** [comment]
can confirm. Arch, gdb 14.2:
```
$ cat .gdbinit
set debuginfod enabled on
set disassembly-flavor intel
source ~/.peda/peda.py
$ gdb
/home/olk/.peda/peda.py:151: SyntaxWarning: invalid escape sequence '\['
  p = re.compile("(.*)\[(.*)\]") # DWORD PTR [esi+eax*1]
/home/olk/.peda/peda.py:373: SyntaxWarning: invalid escape sequence '\s'
  p = re.compile(".*exec file:\s*`(.*)'")
/home/olk/.peda/peda.py:550: SyntaxWarning: invalid escape sequence '\d'
  p = re.compile("^(\d*)\s*(.*breakpoint)\s*(keep|del)\s*(y|n)\s*(0x[^ ]*)\s*(.*)")
/home/olk/.peda/peda.py:554: SyntaxWarning: invalid escape sequence '\d'
  p = re.compile("^(\d*)\s*(.*point)\s*(keep|del)\s*(y|n)\s*(.*)")
/home/olk/.peda/peda.py:567: SyntaxWarning: invalid escape sequence '\d'
  m = re.match("in.*at(.*:\d*)", what)
/home/olk/.peda/peda.py:596: SyntaxWarning: invalid escape sequence '\d'
  m = re.match("^(\d*).*", line)
/home/olk/.peda/peda.py:916: SyntaxWarning: invalid escape sequence '\s'
  p = re.compile("\s*(0x[^ ]*).*?:\s*([^ ]*)\s*(.*)")
/home/olk/.peda/peda.py:918: SyntaxWarning: invalid escape sequence '\s'
  p = re.compile("(.*?)\s*<.*?>\s*([^ ]*)\s*(.*)")
/home/olk/.peda/peda.py:937: SyntaxWarning: invalid escape sequence '\['
  p = re.compile(".*mov.*\[esp(.*)\],")
/home/olk/.peda/peda.py:969: SyntaxWarning: invalid escape sequence '\s'
  p = re.compile(":\s*([^ ]*)\s*(.*),")
/home/olk/.peda/peda.py:1116: SyntaxWarning: invalid escape sequence '\s'
  p = re.compile(".*?:\s*(.*)")
/home/olk/.peda/peda.py:1223: SyntaxWarning: invalid escape sequence '\s'
  p = re.compile(".*?:\s*[^ ]*\s*(.* PTR ).*(0x[^ ]*)")
/home/olk/.peda/peda.py:1226: SyntaxWarning: invalid escape sequence '\s'
  p = re.compile(".*?:\s.*\s(0x[^ ]*|\w+)")
/home/olk/.peda/peda.py:1235: SyntaxWarning: invalid escape sequence '\s'
  p = re.compile(".*?:\s*[^ ]*\s*(.* PTR ).*\[(.*)\]")
/home/olk/.peda/peda.py:1430: SyntaxWarning: invalid escape sequence '\s'
  pattern = re.compile("([^\n]*)\s*  ([0-9a-f][^-\s]*)-([^\s]*) \[.*\]\s([^/]*).*  (.*)")
/home/olk/.peda/peda.py:2096: SyntaxWarning: invalid escape sequence '\s'
  p = re.compile(".*?0x[^ ]*?\s(.*)")
/home/olk/.peda/peda.py:2114: SyntaxWarning: invalid escape sequence '\s'
  p = re.compile(".*?0x[^ ]*?\s(.*)")
/home/olk/.peda/peda.py:2214: SyntaxWarning: invalid escape sequence '\s'
  p = re.compile("Entry point: ([^\s]*)")
/home/olk/.peda/peda.py:2242: SyntaxWarning: invalid escape sequence '\s'
  p = re.compile("\s*(0x[^-]*)->(0x[^ ]*) at (0x[^:]*):\s*([^ ]*)\s*(.*)")
/home/olk/.peda/peda.py:2316: SyntaxWarning: invalid escape sequence '\s'
  m = re.findall(".*(0x[^ ]*)\s*%s" % re.escape(symname), out)
/home/olk/.peda/peda.py:2416: SyntaxWarning: invalid escape sequence '\['
  p = re.compile(".*\[.*\] (\.[^ ]*) [^0-9]* ([^ ]*) [^ ]* ([^ ]*)(.*)")
/home/olk/.peda/peda.py:2474: SyntaxWarning: invalid escape sequence '\s'
  p = re.compile("[^\n]*\s*(0x[^ ]*) - (0x[^ ]*) is (\.[^ ]*) in (.*)")
/home/olk/.peda/peda.py:2681: SyntaxWarning: invalid escape sequence '\ '
  if re.search(re.escape(asmcode).replace("\ ",".*").replace("\?",".*"), asmcode_rs)\
/home/olk/.peda/peda.py:2681: SyntaxWarning: invalid escape sequence '\?'
  if re.search(re.escape(asmcode).replace("\ ",".*").replace("\?",".*"), asmcode_rs)\
/home/olk/.peda/peda.py:2832: SyntaxWarning: invalid escape sequence '\ '
  pattern = re.compile(b'|'.join(JMPCALL).replace(b' ', b'\ '))
/home/olk/.peda/peda.py:3414: SyntaxWarning: invalid escape sequence '\['
  m = re.search(".*\[(.*)\]|.*?s:(0x[^ ]*)", exp)
/home/olk/.peda/peda.py:3519: SyntaxWarning: invalid escape sequence '\['
  sock = re.search("socket:\[(.*)\]", rpath)
/home/olk/.peda/peda.py:3529: SyntaxWarning: invalid escape sequence '\s'
  ppid = re.search("PPid:\s*([^\s]*)", status).group(1)
/home/olk/.peda/peda.py:3531: SyntaxWarning: invalid escape sequence '\s'
  uid = re.search("Uid:\s*([^\n]*)", status).group(1)
/home/olk/.peda/peda.py:3533: SyntaxWarning: invalid escape sequence '\s'
  gid = re.search("Gid:\s*([^\n]*)", status).group(1)
/home/olk/.peda/peda.py:4125: SyntaxWarning: invalid escape sequence '\s'
  p = re.compile(".*?:\s*[^ ]*\s*([^,]*),(.*)")
Traceback (most recent call last):
  File "/home/olk/.peda/peda.py", line 30, in <module>
    from six.moves import range
ModuleNotFoundError: No module named 'six.moves'
(gdb)
```

**Comment by zetef** [comment]
> can confirm. Arch, gdb 14.2:
> 
> ```
> $ cat .gdbinit
> set debuginfod enabled on
> set disassembly-flavor intel
> source ~/.peda/peda.py
> $ gdb
> /home/olk/.peda/peda.py:151: SyntaxWarning: invalid escape sequence '\['
>   p = re.compile("(.*)\[(.*)\]") # DWORD PTR [esi+eax*1]
> /home/olk/.peda/peda.py:373: SyntaxWarning: invalid escape sequence '\s'
>   p = re.compile(".*exec file:\s*`(.*)'")
> /home/olk/.peda/peda.py:550: SyntaxWarning: invalid escape sequence '\d'
>   p = re.compile("^(\d*)\s*(.*breakpoint)\s*(keep|del)\s*(y|n)\s*(0x[^ ]*)\s*(.*)")
> /home/olk/.peda/peda.py:554: SyntaxWarning: invalid escape sequence '\d'
>   p = re.compile("^(\d*)\s*(.*point)\s*(keep|del)\s*(y|n)\s*(.*)")
> /home/olk/.peda/peda.py:567: SyntaxWarning: invalid escape sequence '\d'
>   m = re.match("in.*at(.*:\d*)", what)
> /home/olk/.peda/peda.py:596: SyntaxWarning: invalid escape sequence '\d'
>   m = re.match("^(\d*).*", line)
> /home/olk/.peda/peda.py:916: SyntaxWarning: invalid escape sequence '\s'
>   p = re.compile("\s*(0x[^ ]*).*?:\s*([^ ]*)\s*(.*)")
> /home/olk/.peda/peda.py:918: SyntaxWarning: invalid escape sequence '\s'
>   p = re.compile("(.*?)\s*<.*?>\s*([^ ]*)\s*(.*)")
> /home/olk/.peda/peda.py:937: SyntaxWarning: invalid escape sequence '\['
>   p = re.compile(".*mov.*\[esp(.*)\],")
> /home/olk/.peda/peda.py:969: SyntaxWarning: invalid escape sequence '\s'
>   p = re.compile(":\s*([^ ]*)\s*(.*),")
> /home/olk/.peda/peda.py:1116: SyntaxWarning: invalid escape sequence '\s'
>   p = re.compile(".*?:\s*(.*)")
> /home/olk/.peda/peda.py:1223: SyntaxWarning: invalid escape sequence '\s'
>   p = re.compile(".*?:\s*[^ ]*\s*(.* PTR ).*(0x[^ ]*)")
> /home/olk/.peda/peda.py:1226: SyntaxWarning: invalid escape sequence '\s'
>   p = re.compile(".*?:\s.*\s(0x[^ ]*|\w+)")
> /home/olk/.peda/peda.py:1235: SyntaxWarning: invalid escape sequence '\s'
>   p = re.compile(".*?:\s*[^ ]*\s*(.* PTR ).*\[(.*)\]")
> /home/olk/.peda/peda.py:1430: SyntaxWarning: invalid escape sequence '\s'
>   pattern = re.compile("([^\n]*)\s*  ([0-9a-f][^-\s]*)-([^\s]*) \[.*\]\s([^/]*).*  (.*)")
> /home/olk/.peda/peda.py:2096: SyntaxWarning: invalid escape sequence '\s'
>   p = re.compile(".*?0x[^ ]*?\s(.*)")
> /home/olk/.peda/peda.py:2114: SyntaxWarning: invalid escape sequence '\s'
>   p = re.compile(".*?0x[^ ]*?\s(.*)")
> /home/olk/.peda/peda.py:2214: SyntaxWarning: invalid escape sequence '\s'
>   p = re.compile("Entry point: ([^\s]*)")
> /home/olk/.peda/peda.py:2242: SyntaxWarning: invalid escape sequence '\s'
>   p = re.compile("\s*(0x[^-]*)->(0x[^ ]*) at (0x[^:]*):\s*([^ ]*)\s*(.*)")
> /home/olk/.peda/peda.py:2316: SyntaxWarning: invalid escape sequence '\s'
>   m = re.findall(".*(0x[^ ]*)\s*%s" % re.escape(symname), out)
> /home/olk/.peda/peda.py:2416: SyntaxWarning: invalid escape sequence '\['
>   p = re.compile(".*\[.*\] (\.[^ ]*) [^0-9]* ([^ ]*) [^ ]* ([^ ]*)(.*)")
> /home/olk/.peda/peda.py:2474: SyntaxWarning: invalid escape sequence '\s'
>   p = re.compile("[^\n]*\s*(0x[^ ]*) - (0x[^ ]*) is (\.[^ ]*) in (.*)")
> /home/olk/.peda/peda.py:2681: SyntaxWarning: invalid escape sequence '\ '
>   if re.search(re.escape(asmcode).replace("\ ",".*").replace("\?",".*"), asmcode_rs)\
> /home/olk/.peda/peda.py:2681: SyntaxWarning: invalid escape sequence '\?'
>   if re.search(re.escape(asmcode).replace("\ ",".*").replace("\?",".*"), asmcode_rs)\
> /home/olk/.peda/peda.py:2832: SyntaxWarning: invalid escape sequence '\ '
>   pattern = re.compile(b'|'.join(JMPCALL).replace(b' ', b'\ '))
> /home/olk/.peda/peda.py:3414: SyntaxWarning: invalid escape sequence '\['
>   m = re.search(".*\[(.*)\]|.*?s:(0x[^ ]*)", exp)
> /home/olk/.peda/peda.py:3519: SyntaxWarning: invalid escape sequence '\['
>   sock = re.search("socket:\[(.*)\]", rpath)
> /home/olk/.peda/peda.py:3529: SyntaxWarning: invalid escape sequence '\s'
>   ppid = re.search("PPid:\s*([^\s]*)", status).group(1)
> /home/olk/.peda/peda.py:3531: SyntaxWarning: invalid escape sequence '\s'
>   uid = re.search("Uid:\s*([^\n]*)", status).group(1)
> /home/olk/.peda/peda.py:3533: SyntaxWarning: invalid escape sequence '\s'
>   gid = re.search("Gid:\s*([^\n]*)", status).group(1)
> /home/olk/.peda/peda.py:4125: SyntaxWarning: invalid escape sequence '\s'
>   p = re.compile(".*?:\s*[^ ]*\s*([^,]*),(.*)")
> Traceback (most recent call last):
>   File "/home/olk/.peda/peda.py", line 30, in <module>
>     from six.moves import range
> ModuleNotFoundError: No module named 'six.moves'
> (gdb)
> ```

can confirm the invalid sequence warnings.
regarding the error for module six I recommend force reinstalling the peda package from pacman

**Comment by punixcorn** [comment]
### 1.for SyntaxWarning 
you can fix this by adding r to the strings
eg 
```py
 p = re.compile(r"(.*)\[(.*)\]") # DWORD PTR [esi+eax*1]
```
to make it raw string, pull request #178  fixes this.

---

### 2.for `six.moves` not found
you can use 
```bash
pip install six
```
or if using arch, install from the repos
```bash
sudo pacman -S python-six
```
and remove the `six.py` in the `lib` 
so it uses the global ones and not the local one found in `lib`

**Comment by MetinSAYGIN** [comment]
For Syntax warning just replace ~/peda/peda.py by this one https://raw.githubusercontent.com/punixcorn/peda/master/peda.py

For the six module not found i resolved it by deleting it from the lib folder, so it uses the global six module of my system.
You can just move it with mv ~/peda/lib/six.py ../

**Comment by liudonghua123** [comment]
I have the similar issue, it seems to be the new python's behavior. see https://stackoverflow.com/questions/52335970/how-to-fix-syntaxwarning-invalid-escape-sequence-in-python.

Need to update the code!!!

You can also disable this warnings by using `export PYTHONWARNINGS="ignore"`, see https://stackoverflow.com/questions/14463277/how-to-disable-python-warnings#:~:text=e.%20python%202.7)-,export%20PYTHONWARNINGS%3D%22ignore%22,-Test%20like%20this.

<details><summary>Details</summary>

```shell
└─$ gdb ./stack_overflow_32
GNU gdb (Debian 13.2-1+b2) 13.2
Copyright (C) 2023 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
/home/liudonghua/peda/peda.py:151: SyntaxWarning: invalid escape sequence '\['
  p = re.compile("(.*)\[(.*)\]") # DWORD PTR [esi+eax*1]
/home/liudonghua/peda/peda.py:373: SyntaxWarning: invalid escape sequence '\s'
  p = re.compile(".*exec file:\s*`(.*)'")
/home/liudonghua/peda/peda.py:550: SyntaxWarning: invalid escape sequence '\d'
  p = re.compile("^(\d*)\s*(.*breakpoint)\s*(keep|del)\s*(y|n)\s*(0x[^ ]*)\s*(.*)")
/home/liudonghua/peda/peda.py:554: SyntaxWarning: invalid escape sequence '\d'
  p = re.compile("^(\d*)\s*(.*point)\s*(keep|del)\s*(y|n)\s*(.*)")
/home/liudonghua/peda/peda.py:567: SyntaxWarning: invalid escape sequence '\d'
  m = re.match("in.*at(.*:\d*)", what)
/home/liudonghua/peda/peda.py:596: SyntaxWarning: invalid escape sequence '\d'
  m = re.match("^(\d*).*", line)
/home/liudonghua/peda/peda.py:916: SyntaxWarning: invalid escape sequence '\s'
  p = re.compile("\s*(0x[^ ]*).*?:\s*([^ ]*)\s*(.*)")
/home/liudonghua/peda/peda.py:918: SyntaxWarning: invalid escape sequence '\s'
  p = re.compile("(.*?)\s*<.*?>\s*([^ ]*)\s*(.*)")
/home/liudonghua/peda/peda.py:937: SyntaxWarning: invalid escape sequence '\['
  p = re.compile(".*mov.*\[esp(.*)\],")
/home/liudonghua/peda/peda.py:969: SyntaxWarning: invalid escape sequence '\s'
  p = re.compile(":\s*([^ ]*)\s*(.*),")
/home/liudonghua/peda/peda.py:1116: SyntaxWarning: invalid escape sequence '\s'
  p = re.compile(".*?:\s*(.*)")
/home/liudonghua/peda/peda.py:1223: SyntaxWarning: invalid escape sequence '\s'
  p = re.compile(".*?:\s*[^ ]*\s*(.* PTR ).*(0x[^ ]*)")
/home/liudonghua/peda/peda.py:1226: SyntaxWarning: invalid escape sequence '\s'
  p = re.compile(".*?:\s.*\s(0x[^ ]*|\w+)")
/home/liudonghua/peda/peda.py:1235: SyntaxWarning: invalid escape sequence '\s'
  p = re.compile(".*?:\s*[^ ]*\s*(.* PTR ).*\[(.*)\]")
/home/liudonghua/peda/peda.py:1430: SyntaxWarning: invalid escape sequence '\s'
  pattern = re.compile("([^\n]*)\s*  ([0-9a-f][^-\s]*)-([^\s]*) \[.*\]\s([^/]*).*  (.*)")
/home/liudonghua/peda/peda.py:2096: SyntaxWarning: invalid escape sequence '\s'
  p = re.compile(".*?0x[^ ]*?\s(.*)")
/home/liudonghua/peda/peda.py:2114: SyntaxWarning: invalid escape sequence '\s'
  p = re.compile(".*?0x[^ ]*?\s(.*)")
/home/liudonghua/peda/peda.py:2214: SyntaxWarning: invalid escape sequence '\s'
  p = re.compile("Entry point: ([^\s]*)")
/home/liudonghua/peda/peda.py:2242: SyntaxWarning: invalid escape sequence '\s'
  p = re.compile("\s*(0x[^-]*)->(0x[^ ]*) at (0x[^:]*):\s*([^ ]*)\s*(.*)")
/home/liudonghua/peda/peda.py:2316: SyntaxWarning: invalid escape sequence '\s'
  m = re.findall(".*(0x[^ ]*)\s*%s" % re.escape(symname), out)
/home/liudonghua/peda/peda.py:2416: SyntaxWarning: invalid escape sequence '\['
  p = re.compile(".*\[.*\] (\.[^ ]*) [^0-9]* ([^ ]*) [^ ]* ([^ ]*)(.*)")
/home/liudonghua/peda/peda.py:2474: SyntaxWarning: invalid escape sequence '\s'
  p = re.compile("[^\n]*\s*(0x[^ ]*) - (0x[^ ]*) is (\.[^ ]*) in (.*)")
/home/liudonghua/peda/peda.py:2681: SyntaxWarning: invalid escape sequence '\ '
  if re.search(re.escape(asmcode).replace("\ ",".*").replace("\?",".*"), asmcode_rs)\
/home/liudonghua/peda/peda.py:2681: SyntaxWarning: invalid escape sequence '\?'
  if re.search(re.escape(asmcode).replace("\ ",".*").replace("\?",".*"), asmcode_rs)\
/home/liudonghua/peda/peda.py:2832: SyntaxWarning: invalid escape sequence '\ '
  pattern = re.compile(b'|'.join(JMPCALL).replace(b' ', b'\ '))
/home/liudonghua/peda/peda.py:3414: SyntaxWarning: invalid escape sequence '\['
  m = re.search(".*\[(.*)\]|.*?s:(0x[^ ]*)", exp)
/home/liudonghua/peda/peda.py:3519: SyntaxWarning: invalid escape sequence '\['
  sock = re.search("socket:\[(.*)\]", rpath)
/home/liudonghua/peda/peda.py:3529: SyntaxWarning: invalid escape sequence '\s'
  ppid = re.search("PPid:\s*([^\s]*)", status).group(1)
/home/liudonghua/peda/peda.py:3531: SyntaxWarning: invalid escape sequence '\s'
  uid = re.search("Uid:\s*([^\n]*)", status).group(1)
/home/liudonghua/peda/peda.py:3533: SyntaxWarning: invalid escape sequence '\s'
  gid = re.search("Gid:\s*([^\n]*)", status).group(1)
/home/liudonghua/peda/peda.py:4125: SyntaxWarning: invalid escape sequence '\s'
  p = re.compile(".*?:\s*[^ ]*\s*([^,]*),(.*)")
Traceback (most recent call last):
  File "/home/liudonghua/peda/peda.py", line 30, in <module>
    from six.moves import range
ModuleNotFoundError: No module named 'six.moves'
Reading symbols from ./stack_overflow_32...
(gdb) exit

┌──(liudonghua㉿DESKTOP-9DGFF40)-[~/ctf]
└─$
┌──(liudonghua㉿DESKTOP-9DGFF40)-[~/ctf]
└─$ export PYTHONWARNINGS="ignore"

┌──(liudonghua㉿DESKTOP-9DGFF40)-[~/ctf]
└─$ gdb ./stack_overflow_32
GNU gdb (Debian 13.2-1+b2) 13.2
Copyright (C) 2023 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Traceback (most recent call last):
  File "/home/liudonghua/peda/peda.py", line 30, in <module>
    from six.moves import range
ModuleNotFoundError: No module named 'six.moves'
Reading symbols from ./stack_overflow_32...
(gdb)
```
</details>

**Comment by liudonghua123** [comment]
And for `ModuleNotFoundError: No module named 'six.moves'` issue, I tried `python3.12 -m pip install six` but it doesn't work, and I fixed by `cp /usr/lib/python3/dist-packages/six.py /home/liudonghua/peda/lib/six.py` finally.

<details><summary>Details</summary>

```
┌──(liudonghua㉿DESKTOP-9DGFF40)-[~/ctf]
└─$ gdb
GNU gdb (Debian 13.2-1+b2) 13.2
Copyright (C) 2023 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word".
Traceback (most recent call last):
  File "/home/liudonghua/peda/peda.py", line 30, in <module>
    from six.moves import range
ModuleNotFoundError: No module named 'six.moves'
(gdb) python import sys; print(sys.path)
['/home/liudonghua/peda/lib/', '/usr/share/gdb/python', '/usr/lib/python312.zip', '/usr/lib/python3.12', '/usr/lib/python3.12/lib-dynload', '/usr/local/lib/python3.12/dist-packages', '/usr/lib/python3/dist-packages', '/usr/lib/python3.12/dist-packages']
(gdb) from six.moves import range
Undefined command: "from".  Try "help".
(gdb) python from six.moves import range
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'six.moves'
Error while executing Python code.
(gdb) python import six; print(six.__file__)
/home/liudonghua/peda/lib/six.py
(gdb) exit

┌──(liudonghua㉿DESKTOP-9DGFF40)-[~/ctf]
└─$ python3.12
Python 3.12.4 (main, Jul 15 2024, 12:17:32) [GCC 13.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import six
>>> from six.moves import range
>>> six.__file__
'/usr/lib/python3/dist-packages/six.py'
>>> exit()

┌──(liudonghua㉿DESKTOP-9DGFF40)-[~/ctf]
└─$ ll /usr/lib/python3/dist-packages/six.py /home/liudonghua/peda/lib/six.py
-rw-r--r-- 1 liudonghua liudonghua 34549 Oct 28 22:24 /home/liudonghua/peda/lib/six.py
-rw-r--r-- 1 root       root       34549 Mar 16  2024 /usr/lib/python3/dist-packages/six.py

┌──(liudonghua㉿DESKTOP-9DGFF40)-[~/ctf]
└─$

┌──(liudonghua㉿DESKTOP-9DGFF40)-[~/ctf]
└─$ cp /home/liudonghua/peda/lib/six.py /home/liudonghua/peda/lib/six.py.old

┌──(liudonghua㉿DESKTOP-9DGFF40)-[~/ctf]
└─$ cp /usr/lib/python3/dist-packages/six.py /home/liudonghua/peda/lib/six.py

┌──(liudonghua㉿DESKTOP-9DGFF40)-[~/ctf]
└─$ gdb
GNU gdb (Debian 13.2-1+b2) 13.2
Copyright (C) 2023 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word".
gdb-peda$
```

</details>

**Comment by zhaoxy0118** [comment]
it's not work my pc
![image](https://github.com/user-attachments/assets/0c6acac0-607a-4815-9155-b3b11b653728)

**Comment by liudonghua123** [comment]
> it's not work my pc
> ![image](https://github.com/user-attachments/assets/0c6acac0-607a-4815-9155-b3b11b653728)
> 
> 

from the picture, i didn't see such error like `ModuleNotFoundError: No module named 'six.moves'`, and it's working for you.

**Comment by zhaoxy0118** [comment]
oh，yes，it's working for me。Thanks

**Comment by Kuro-orzz** [comment]
i fixed this on my repository, you guys can go and check that

**Comment by somnico** [comment]
> i fixed this on my repository, you guys can go and check that

Awesome that you made a fork, I do however still get these. Is it the same fix?

```
/home/kali/tools/gdb/peda/lib/utils.py:526: SyntaxWarning: invalid escape sequence '\s'
  m = re.search(".*(0x[^ ]*).*:\s*([^ ]*)", line)
/home/kali/tools/gdb/peda/lib/utils.py:543: SyntaxWarning: invalid escape sequence '\s'
  addr = re.search("(0x[^\s]*)", prefix)
/home/kali/tools/gdb/peda/lib/utils.py:592: SyntaxWarning: invalid escape sequence '\('
  charset += ['!"#$%&\()*+,-./:;<=>?@[]^_{|}~'] # string.punctuation
/home/kali/tools/gdb/peda/lib/nasm.py:85: SyntaxWarning: invalid escape sequence '\s'
  pattern = re.compile("([0-9A-F]{8})\s*([^\s]*)\s*(.*)")
```

**Comment by punixcorn** [comment]
> > i fixed this on my repository, you guys can go and check that
> 
> Awesome that you made a fork, I do however still get these. Is it the same fix?
> 
> ```
> /home/kali/tools/gdb/peda/lib/utils.py:526: SyntaxWarning: invalid escape sequence '\s'
>   m = re.search(".*(0x[^ ]*).*:\s*([^ ]*)", line)
> /home/kali/tools/gdb/peda/lib/utils.py:543: SyntaxWarning: invalid escape sequence '\s'
>   addr = re.search("(0x[^\s]*)", prefix)
> /home/kali/tools/gdb/peda/lib/utils.py:592: SyntaxWarning: invalid escape sequence '\('
>   charset += ['!"#$%&\()*+,-./:;<=>?@[]^_{|}~'] # string.punctuation
> /home/kali/tools/gdb/peda/lib/nasm.py:85: SyntaxWarning: invalid escape sequence '\s'
>   pattern = re.compile("([0-9A-F]{8})\s*([^\s]*)\s*(.*)")
> ```

The issue from file utils.py in the lib/ directory
you can fix it by  adding r to the strings or replace b'...' with r'...' , based on the warning check my pull request on #179

**Comment by fatherofphysics** [comment]
<img width="539" height="99" alt="Image" src="https://github.com/user-attachments/assets/e5571543-b4d0-4fde-a102-5bcb831f932e" />


# warning fix
export PYTHONWARNINGS="ignore"

# six moves
sudo cp /usr/lib/python3/dist-packages/six.py /home/xct/peda/lib/six.py

this has fixed all the issues thanks to [liudonghua](https://github.com/liudonghua123)

<img width="815" height="436" alt="Image" src="https://github.com/user-attachments/assets/912a954a-40e7-4580-82b4-a65efdd7bd37" />
